### ISSUE TITLE
Module '"pusher-js"' has no exported member 'Config'

### ISSUE THREAD

**Issue by snaptopixel** [nikolalsvk/pusher-js-mock#25]
Using Typescript with these versions will not compile:
```
"pusher-js": "^6.0.3",
"pusher-js-mock": "^0.3.1",
```
Pusher mock's types specify: `import { Config } from "pusher-js";` but `Config` is not exported in this version of `pusher-js`

**Comment by snaptopixel** [comment]
FWIW, I got around this for now… (I'm using .ts files for tests)

```ts
import Pusher from 'pusher-js'
const PusherMock = require('pusher-js-mock').PusherMock
const pusher = new PusherMock() as Pusher
```

**Comment by nikolalsvk** [comment]
Hey, @snaptopixel, thanks for creating an issue about this!

@mayteio can you help out on this one? I see that the `Config` has been changed to `Option` and I'm not sure whether we should support custom authorization at this point. I feel like this is something that should be tested outside this library, it is adding too much complexity, what do you think?

**Comment by mayteio** [comment]
Hey @nikolalsvk, if you want to roll back to drop support for custom authorization that's your call. Personally I feel the package should replicate the real thing as much as possible, which is what I was trying to achieve with custom auth (we used custom auth in our project thus the need to mock it).

If it's a simple case of switching the `Config` type to `Option` surely that's something we can do here?

**Comment by nikolalsvk** [comment]
Thanks for responding, @mayteio. Do you think we could achieve a similar thing without being dependant on the pusher-js?

For example, can we try to support custom authorization without import `Config` or `Option`? This will allow for easier support of previous and new versions of the pusher-js.

**Comment by mayteio** [comment]
OK, so this problem stems because `pusher-js` [released official types](https://github.com/pusher/pusher-js/blob/master/CHANGELOG.md#510-2020-02-11) that are incompatible with `@types/pusher-js` (that was the only option available for types when presence channel work was being done).

It gives to reason that if someone is using `pusher-js-mock` to test their app they have `pusher-js` as a dependency too, so I don't think it's farfetched to rely on it.

A good example is in the 'presence-channel' example where the official `pusher-js` is being mocked by jest.

I've created #29 to remove the `@types/pusher-js` dependency and fix imports. 

It's probably worth noting that the project relies on itself via the examples. The examples should probably have their own package.json to avoid this.

**Comment by nikolalsvk** [comment]
This should not happen now with the [new 0.3.2 version](https://github.com/nikolalsvk/pusher-js-mock/releases/tag/0.3.2). Can you check @snaptopixel when you have time? I'll close this in the meantime and reopen if it's not fixed.
